name: recent-activity

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Recent GitHub Activity - Profile Readme
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          README_FILE: "readme.md"